#!/bin/bash

###############################################################################
# Project : Human Germline Variant Calling using GATK Best Practices
#
# Script  : 07_variantfiltration.sh
#
# Purpose :
# Apply hard filters to raw germline variants generated by
# GATK HaplotypeCaller.
#
# Input :
#   results/variants/NIST7035_raw_variants.vcf.gz
#
# Reference :
#   data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
#
# Output :
#   results/variants/NIST7035_filtered_variants.vcf.gz
#
###############################################################################

set -euo pipefail

echo "==============================================="
echo "Step 7 : Variant Filtration"
echo "==============================================="

gatk VariantFiltration \
-R data/reference/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna \
-V results/variants/NIST7035_raw_variants.vcf.gz \
-O results/variants/NIST7035_filtered_variants.vcf.gz \
--filter-name "QD2" \
--filter-expression "QD < 2.0" \
--filter-name "FS60" \
--filter-expression "FS > 60.0" \
--filter-name "MQ40" \
--filter-expression "MQ < 40.0"

echo ""
echo "Variant filtration completed successfully."
echo "Output:"
echo "  - results/variants/NIST7035_filtered_variants.vcf.gz"
